import os

Import('env','dirs')
objects = []
input_files = []
for d in dirs:
    objs, inputs = SConscript("%s/SConscript" % d, exports='env')
    if objs != None:
        objects.extend(objs)
    if inputs != None and len(inputs) != 0:
        input_files.extend(inputs)

objects.append("main.cpp")
tests_exec = env.Program('tests_exec', objects, LIBS=["mlearning", "gtest"])
Return("tests_exec", "input_files")



