import os
import os.path
import glob
from colorizer import colorizer


def get_files(directory, ext, recursive=True, level=0):
    """
        Get all the files with an given extension from a directory 
        @param directory
        @param ext extension of the files
        @param recursive If true, the search is recursive
        @paran level Maximum level of recursion (TODO)   
    """
    cwd = os.getcwd()
    contents = os.listdir(directory)

    os.chdir( directory )
    files = []
    for c in contents:
        if os.path.isdir(c) and recursive:
            files.extend(get_files(c,ext))
        elif os.path.isfile(c):
            files.append(c) 
    os.chdir( cwd )
    files = [os.path.join(directory,f) for f in files]
    return files


def check_headers(conf, files):
    for d in files:
        if not conf.CheckCXXHeader(d):
            print "Could not find the required header",d




home=os.environ["HOME"]
path=os.environ["PATH"]
term = os.environ["TERM"]

env = Environment()
env['ENV'] = {'PATH' : path, 'TERM' : term, 'HOME' : home}
env['CPPPATH'] = ["include",
                  "/usr/include",
                  "/usr/include/eigen3",
                  ] # search for includes
env['CXXFLAGS'] = ["-std=c++0x"] 
env['PREFIX'] = ["build"] 

# for nice compiling colors
col = colorizer()
col.colorize(env)


# preparation of repositories
env.Repository('')
env.Repository('tests')


# configure
conf = Configure(env)
required_headers = ["boost/shared_ptr.hpp", "eigen3/Eigen/Dense", ]
check_headers(conf, required_headers)




# Build dynamic library
cwd = os.getcwd()
src = os.path.join(cwd,"src")
sources = get_files(src, "*.cpp")
libmlearning = env.SharedLibrary('mlearning', sources)

# Install lib
env.Install('$PREFIX/lib', libmlearning)

# install includes


# build a program
# env.Program('test', "test.cpp", LIBS=['mlearn'],LIBPATH="." )


# build the tests 
env['CPPPATH'].append(["/chime1/home/javi/gtest-1.6.0/include"])
env['LIBPATH'] = ["/chime1/home/javi/gtest-1.6.0/lib",'.']
print env["LIBPATH"]
src = os.path.join(cwd,"tests")
test_sources = get_files(src, "*.cpp")
env.Program('test', test_sources, LIBS=['mlearning', "gtest"])



